# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2025 Jonas Tobias Hopusch <git@jotoho.de>

version: 2
multi-ecosystem-groups:
  application:
    schedule: "monthly"
updates:
  - package-ecosystem: "npm"
    multi-ecosystem-group: "application"
    patterns: ["*"]
    directory: "/"
    assignees:
      - "jotoho"
    groups:
      compatible:
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "github-actions"
    schedule:
      interval: "monthly"
    directory: "/"
    assignees:
      - "jotoho"
    groups:
      compatible:
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: "pip"
    multi-ecosystem-group: "application"
    patterns: ["*"]
    directory: "/functions/invite-to-team/"
    assignees:
      - "jotoho"
    groups:
      compatible:
        update-types:
          - "patch"
          - "minor"
