# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2025 Jonas Tobias Hopusch <git@jotoho.de>

version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    directory: "/"
  - package-ecosystem: "github-actions"
    schedule:
      interval: "weekly"
    directory: "/"
