# SPDX-FileCopyrightText: 2023-2026 Jonas Tobias Hopusch <git@jotoho.de>
# SPDX-License-Identifier: CC0-1.0

name: 'Process Github Threads'

on:
  issues:
    types: [assigned, unassigned, milestoned, demilestoned]
  issue_comment:
    types: [created]
  discussion_comment:
    types: [created]
  workflow_dispatch:

jobs:
  stale:
    name: Process stale threads
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
      pull-requests: write
      discussions: write
    concurrency:
      group: stale
      cancel-in-progress: true
    steps:
      - uses: actions/stale@v10.2.0
        with:
          exempt-all-assignees: true
          exempt-all-milestones: true
  lockthreads:
    name: Scan and Lock closed threads
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      issues: write
      pull-requests: write
      discussions: write
    concurrency:
      group: lockthreads
      cancel-in-progress: true
    steps:
      - uses: dessant/lock-threads@v6.0.0
        with:
          issue-inactive-days: '28'
          pr-inactive-days: '28'
          discussion-inactive-days: '28'
